name: Docker Image CI - Contas.Migrations

on:
  push:
    paths:
      - 'src/Usadosbr.Contas.Migrations/**'
    branches: [ main ]
    tags:
      - v*
  pull_request:
    paths:
      - 'src/Usadosbr.Contas.Migrations/**'
    branches: [ main ]
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push image'
      uses: actions/checkout@v2

    - run: |
        docker build . --file src/Usadosbr.Contas.Migrations/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/contas.migrations:v1
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/contas.migrations:v1
